### ISSUE TITLE
Change window name to distinguish quickly between open instances

### ISSUE THREAD

**Issue by netchkin** [Scarfsail/AdvancedLogViewer#21]

**Comment by Scarfsail** [comment]
The window name consist of ALV - LogFileName where LogFileName is actually opened log file name to quickly distinguish between open instances. Please be more specific about this feature request.

**Comment by Scarfsail** [comment]
Closing because of lack of more information, please re-open when more information is provided.

**Comment by Scarfsail** [comment]
Closing because of lack of more information, please re-open when more information is provided.

**Comment by Scarfsail** [comment]
Closing because of lack of more information, please re-open when more information is provided.
