### ISSUE TITLE
Support of high DPI monitors

### ISSUE THREAD

**Issue by yuri-tceretian** [Scarfsail/AdvancedLogViewer#25]
It would be great to have the support of high DPI monitors and be able to scale text. 
An interesting thing I noticed: when I open the application settings, the main window scales down back to 100% of regular DPI and becomes very small. A restart helps, though.

**Comment by Scarfsail** [comment]
Please try version 9.x which is built in .NET 5 and also removes the setting page has been replaced by standard winform page as the WPF inside winform caused such issues.

**Comment by yuri-tceretian** [comment]
works great! thanks for the update!
