### ISSUE TITLE
UTF8 support

### ISSUE THREAD

**Issue by Lake292** [Scarfsail/AdvancedLogViewer#3]
UTF8 texts are not interpreted correctly.

Russian text like
"errorMessage":"Пожалуйста, укажите детали прибытия"
is not displayed correctly in AVP:
"errorMessage":"РџРѕР¶Р°Р»СѓР№СЃС‚Р°, СѓРєР°Р¶РёС‚Рµ РґРµС‚Р°Р»Рё РїСЂРёР±С‹С‚РёСЏ"

**Comment by MedviGaile** [comment]
Issue was fixed in 8.0.0+
